# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['lintune_launcher.py'],
    pathex=['src'],
    binaries=[],
    datas=[
        ('src/lintune/resources', 'lintune/resources'),
        ('src/lintune', 'lintune'),
    ],
    hiddenimports=[
        'PyQt6',
        'PyQt6.QtCore',
        'PyQt6.QtGui',
        'PyQt6.QtWidgets',
        'distro',
        'psutil',
        'jinja2',
        'jinja2.ext',
        'lintune',
        'lintune.gui',
        'lintune.gui.main_window',
        'lintune.gui.sidebar',
        'lintune.gui.dashboard',
        'lintune.gui.devices_view',
        'lintune.gui.settings_view',
        'lintune.gui.logs_view',
        'lintune.gui.dialogs',
        'lintune.gui.widgets',
        'lintune.core',
        'lintune.core.distro',
        'lintune.core.validator',
        'lintune.core.installer',
        'lintune.core.package_manager',
        'lintune.core.himmelblau',
        'lintune.core.configurator',
        'lintune.utils',
        'lintune.utils.logger',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='LinTune',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
